# Site settings
title: Everyday Threat Modelling
email: everyday@threatspec.org
description: > # this means to ignore newlines until "baseurl:"
  A series of tutorials introducing Threat Modelling in variety of contexts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: zeroXten
github_username:  zeroXten

# Build settings
markdown: kramdown
